create table car
(
    doors      integer,
    seat_count integer,
    id         bigint not null,
    primary key (id)
);

create table lorry
(
    capacity_kg integer,
    mass_kg     integer,
    id          bigint not null,
    primary key (id)
);

create table manufacturer
(
    id          bigint generated by default as identity,
    description varchar(100) not null,
    name        varchar(100) not null,
    primary key (id)
);

create table vehicle
(
    id              bigint generated by default as identity,
    manufacturer_id bigint,
    model           varchar(100) not null,
    primary key (id)
);

alter table if exists car add constraint FKfugwdpykh9kb35q1quro44hrm foreign key (id) references vehicle;
alter table if exists lorry add constraint FK2f68dn54vl2ud52uhsjlily1m foreign key (id) references vehicle;
alter table if exists vehicle add constraint FKc6y2tuc57qy6qi28dqjeerodl foreign key (manufacturer_id) references manufacturer;
